### ISSUE TITLE
I decided to reopen the source code

### ISSUE THREAD

**Issue by HaoJun0823** [HaoJun0823/GECV#13]
Hello friends, so I see that you guys are following my project a lot lately, so I decided to open source it again.

Therefore, this project was originally open source and closed because we do not want to mislead others for the time being, because our code may be wrong, and the whole project is confusing and irregular.

Since I recently updated some content I was able to drop a lot of the old stuff, so you can focus on GECV II, which rewrote most of the content, at least for the important parts of the PC version, and it works.

The reverse engineering of these tools originated from the work of the main person in charge over the past few years. He told me how the game worked in his spare time, so I wrote the tools and assisted him in localizing the game, which accelerated everything dozens of times. .

I would like to do more but there is no support for us, mainly in terms of technology, work, and labor support, so I will explain our situation here. If improvement does not occur in the near future, I have decided to disband our group.

That's all, hope our results can help you.

**Comment by nachotacos69** [comment]
well for me, I only own a PC and PSP (which I own one), so I translate GE2 and only modify GE2RB
