### ISSUE TITLE
I have published EaterCake: Display monster health

### ISSUE THREAD

**Issue by HaoJun0823** [HaoJun0823/GECV#15]
This tool can display the monster HP in the PC versions of GER and GE2RB.
Version 1002 has instructions in Chinese and English.

Tested in the Chinese community and seems to be working fine so far.
Run this, set up the floating window, and run the game in window mode. When you attack a valid monster, the floating window will pop up to display the monster's health.

https://github.com/HaoJun0823/EaterCake/releases/tag/debug

The game uses a buggy fullscreen topmost method and therefore can only be used in windowed mode.
Overly tweaking the game's win32 code is not something I support, but if anyone has a more stable solution I'll try it.

**Comment by nachotacos69** [comment]
From what I know the aragami HP are in Uint32 formatting, so yeah think can be useful

**Comment by nachotacos69** [comment]
yeah the link 404 💀 I keep forgetting

**Comment by nachotacos69** [comment]
suggestion: i think you should or someone make a tool that can modify a specified mission, although stupid but it sounds okay i guess but for now focus on this one

**Comment by HaoJun0823** [comment]
> suggestion: i think you should or someone make a tool that can modify a specified mission, although stupid but it sounds okay i guess but for now focus on this one

I adjusted the permissions on the repository so you can download EaterCake.

As for the editor and any future stuff you mentioned, I won't do it, we are not focused on the development of Mod tools, developing a tool with a GUI is very complicated, and we do not have any implementation method for this.

From the TR2 tool and our RDP tool that doesn't work properly, version changes of the game make it impossible to develop unified tools, and currently we know even less about the content beyond the PC version.

The author of the Chinese patch and I spent too much time developing a lot of things in the past six months, and in the end there were not many usable things. We used these contents to accomplish what we wanted to do and open source them.

But there are still a large number of interested people who have made more requests and hope that we will continue to do more, but we will not because we are tired and all this is far beyond our own capabilities. Being able to complement BLZ2 is already Extra parts too.

Maybe you think "it all looks very easy. Two Chinese people did everything quietly, so they can mysteriously do more of what everyone wants." I want to say, no, it is very difficult.

**Comment by nachotacos69** [comment]
Yeah, got it, anyways thanks for the link + I'm fixing some stuff along the way for the links for the undub which takes time
