### ISSUE TITLE
Weird Header Version for the GOD EATER

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#20]
yes, the first GOD EATER has a few wacky tr2 header version, though i cant identify where are they are located but i'll send this mission.tr2 for you to inspect with
on the debug command prompt, this shows up
`Think Header Version:131727360`
[mission.zip](https://github.com/HaoJun0823/GECV/files/15242450/mission.zip)

**Comment by HaoJun0823** [comment]
Thanks for your feedback, the issue has been resolved and 1.0.1.5 has been uploaded.
Looking at it in hexadecimal, this is a problem with the headers 0x4-0x7.
We have confirmed that 0x06-0x07 are years, currently 1999, 2000, 2010, 2015.
Among them, the new version is 02 00 DF 07 (2015), and the old version may be DA 07 (2010) or 07 CF (1999), or D0 07 (2010).

I've rewritten part of the logic to direct the year to specific processing.

If you find other years, you can report it to me. Currently 1.0.1.5 is not tested too much. This problem breaks the structure of my editor and stems from me asking the Chinese translator many times before if there are only two versions.
One more thing is new: I do not recommend converting the old and new versions of tr2 at will. Please keep the original version output.

**Comment by HaoJun0823** [comment]
> Thanks for your feedback, the issue has been resolved and 1.0.1.5 has been uploaded. Looking at it in hexadecimal, this is a problem with the headers 0x4-0x7. We have confirmed that 0x06-0x07 are years, currently 1999, 2000, 2010, 2015. Among them, the new version is 02 00 DF 07 (2015), and the old version may be DA 07 (2010) or 07 CF (1999), or D0 07 (2010).
> 
> I've rewritten part of the logic to direct the year to specific processing.
> 
> If you find other years, you can report it to me. Currently 1.0.1.5 is not tested too much. This problem breaks the structure of my editor and stems from me asking the Chinese translator many times before if there are only two versions. One more thing is new: I do not recommend converting the old and new versions of tr2 at will. Please keep the original version output.

@nachotacos69
You need to focus on this.

**Comment by nachotacos69** [comment]
Alright, got it

**Comment by nachotacos69** [comment]
Good Morning everyone. it seems like the current version doesn't let you modify the tr2 file for some reason, At least testing it with a tr2 file that i gathered from [70f92bc5db957c4862ad4a466bd9e117.edat](https://github.com/HaoJun0823/GECV/files/15255903/70f92bc5db957c4862ad4a466bd9e117.zip)

https://github.com/HaoJun0823/GECV/assets/99103531/5d470ff6-a1c8-43a2-bc7b-aa0fb32b223e

**Comment by HaoJun0823** [comment]
> Good Morning everyone. it seems like the current version doesn't let you modify the tr2 file for some reason, At least testing it with a tr2 file that i gathered from [70f92bc5db957c4862ad4a466bd9e117.edat](https://github.com/HaoJun0823/GECV/files/15255903/70f92bc5db957c4862ad4a466bd9e117.zip)

You should upload the tr2 file in question rather than an entire pres.

In addition, if you did not save successfully, the console record is also very important.

**Comment by nachotacos69** [comment]
oh right my bad

**Comment by HaoJun0823** [comment]
> oh right my bad

I extracted this file from your pres and I tested it without any problems.

You should not overwrite the original file, this is more dangerous, although I did not lock the read file.

![image](https://github.com/HaoJun0823/GECV/assets/26188180/87431614-51a3-4552-85ed-bc321b9343d5)

**Comment by nachotacos69** [comment]
man talk about silly things i do, dont worry i should probably fix my ways later on

**Comment by DarkGD123** [comment]
don't sweat it @nachotacos69, we all make mistakes here haha

but anyways @HaoJun0823, the editing/saving works, downside is it freezes the game after translation (check on this image). 
![Screenshot (192)](https://github.com/HaoJun0823/GECV/assets/42462384/f59aa11e-e0bf-4a6b-b983-919e98fcfd2a)
maybe i repacked the Pres in a weird way but i'll fix it along the way
