### ISSUE TITLE
How to Define End Blocks

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#22]
considering how hard it is to identify end blocks for PRES (old to newer variants,  BLZ (version 2 and 4), and some other formats, can you at least give some small ideas?

**Comment by nachotacos69** [comment]
this is kind of interesting. although to define end blocks, its usually on some kind of null strings / bull bytes i believe

**Comment by HaoJun0823** [comment]
What is an "end block"?

**Comment by nachotacos69** [comment]
i think what he meant is something related to where a file stops, like end offset or something like null strings?

take this RIFF AT3 as an example from `PATCH.EDAT`:
- i copied a start offset hex and go to that specific part where AT3 is located
- i copied another offset of AT3 which is the end offsets or whatever you call it
- where it stops containing data is somewhere around the null strings `00`

https://github.com/HaoJun0823/GECV/assets/99103531/93fdd497-7ecd-4b8d-9500-2e5db7d0158f

**Comment by HaoJun0823** [comment]
> i think what he meant is something related to where a file stops, like end offset or something like null strings?
> 
> take this RIFF AT3 as an example from `PATCH.EDAT`:
> 
> * i copied a start offset hex and go to that specific part where AT3 is located
> * i copied another offset of AT3 which is the end offsets or whatever you call it
> * where it stops containing data is somewhere around the null strings `00`
> 
>  start.to.end.mp4

I still don't understand what you guys are talking about.

Most of the data in the game is aligned according to 16 bytes, and if it is less than 16 bytes, it will be aligned with zeros.

#11 This process has been described.

**Comment by HaoJun0823** [comment]
> > i think what he meant is something related to where a file stops, like end offset or something like null strings?
> > take this RIFF AT3 as an example from `PATCH.EDAT`:
> > 
> > * i copied a start offset hex and go to that specific part where AT3 is located
> > * i copied another offset of AT3 which is the end offsets or whatever you call it
> > * where it stops containing data is somewhere around the null strings `00`
> > 
> > start.to.end.mp4
> 
> I still don't understand what you guys are talking about.
> 
> Most of the data in the game is aligned according to 16 bytes, and if it is less than 16 bytes, it will be aligned with zeros.
> 
> #11 This process has been described.

RDP resources will be indexed by pres, We found that some RDPs are aligned at 0x800.

**Comment by nachotacos69** [comment]
ah i see.. maybe i did something a bit bad, so yeah, thanks for clarification

**Comment by nachotacos69** [comment]
i usually just think that where the file actually stops at `\00`, like since there's multiple blz2 or 4 headers i usually go copy the header + data/chunks + and end the copying when i encounter a few consecutives of `\00` well atleast from what i can understand on C# stuff

**Comment by DarkGD123** [comment]
ahh i see, thanks for the clarification @HaoJun0823, also is there any documentation for the PRES? (older variants instead of the PD version)

**Comment by HaoJun0823** [comment]
> ahh i see, thanks for the clarification @HaoJun0823, also is there any documentation for the PRES? (older variants instead of the PC version)

Again, we've been focused on PC from beginning to end, so we don't know the structure of other platforms.

PRES has not changed much, the PC only has six more country data segments.
If you can understand PC, you can also understand other platforms.

**Comment by DarkGD123** [comment]
ahh, okay then 😄

**Comment by HaoJun0823** [comment]
> i usually just think that where the file actually stops at `\00`, like since there's multiple blz2 or 4 headers i usually go copy the header + data/chunks + and end the copying when i encounter a few consecutives of `\00` well atleast from what i can understand on C# stuff but yeah. maybe im just guessing haha

In PRES, all files are indexed, and the file size is recorded in the index.

The game will read these files in 16-byte sizes until the end of the file.
Therefore, files that are not long enough need to be supplemented with 00 to align to 16 bytes.

Adding 00 will not destroy the file structure. PRES and TR2 are strong indexes. BNSF, IS14, and GNF (PC) have their own header information.

BLZ also ends when it reads 00, because the next data block size is 0.

**Comment by nachotacos69** [comment]
ahh, i see. thank you then 🎊
