### ISSUE TITLE
Help for a simple replacement

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#23]
Let's say that I got the start and end offsets of the original file (which the qpckeater gives me because the file names are based on the offsets). We will use 0x800 as a start offset then 0x5E00 as the end offset for this explanation

Now, I want to override "that" part (for example a blz4 file that has either .tr2 or other formats inside of it), 
but the modified one is a bit off after I inflated/compressed it and doesn't match with the original (a bit less or more than the original offset)

Original: 0x800_0x5E00
Modified part: 0x800_0x5A00 (the end offset is less)

What can we do in this situation?

**Comment by nachotacos69** [comment]
🤔

**Comment by DarkGD123** [comment]
Closing due to no response
