### ISSUE TITLE
PRES Problem

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#5]
while processing the PRES files (extraction part), apparently the RAM/Memory usage went very high that it force resets the computer instantly
i hope the developers can fix this

**Comment by nachotacos69** [comment]
hmm.. mine resets all the time when doing that but the chance of happening is pretty low for me, I suggest only opening the tool only, and the rest of the apps are closed.. also have good amount of storage 😀

**Comment by HaoJun0823** [comment]
The developer used an I7 laptop with 16G of memory to use these tools. No crashes occurred, and the performance was acceptable.
The old unpacking and packaging did have memory issues, I rewrote them using .NET 8 (GECV_EX_PRES, GECV_EX_TR2_EDITOR) so the current tools have been tested.
Memory utilization is related to processing speed. These tools were very slow at first, so I used memory for caching. I have considered GC as much as possible.
PRES is the most complex thing. It has 1 or 6 multi-language areas. Each area has 8 data sets, including real references and virtual references, including BLZ4 compression and uncompression. The calculation method of each area is also different. the same.

Android phones can now have 16G of memory, so I recommend upgrading your computer configuration.

**Comment by HaoJun0823** [comment]
> hmm.. mine resets all the time when doing that but the chance of happening is pretty low for me, I suggest only opening the tool only, and the rest of the apps are closed.. also have a good amount of storage 😀

About storage space:
This has something to do with the format of the game.

The game requires a specific file hash when loading qpck, therefore, you need to preserve the order and hash of the source files.
The game uses a file storage that cannot be expressed by the operating system. The pres allows files with the same path and the same name but different configurations. Therefore, in order for the operating system to access these files, all six languages need to be unpacked, and there are a lot of repeated references. 
There are also pres files in pres files, so this is a nested relationship, and you need to decompress layer by layer to have a directory hierarchy.
blz4 files need to be decompressed, gnf has no file header and only has a tag, these files also need to be decompressed.
When translating the game, we prepared almost 200G of hard drive space, which is used to save every file in the process.

**Comment by nachotacos69** [comment]
I have like 4GB memory lmao, yet mine works well as long I don't touch anything

**Comment by DarkGD123** [comment]
ahh I see, thanks for the answer then

**Comment by DarkGD123** [comment]
@HaoJun0823 when will the new update will be released?

**Comment by HaoJun0823** [comment]
> @HaoJun0823 when will the new update will be released?

There won't be a new version here, we've done what we have to do.
These tools successfully fixed Japanese voice and Chinese translation, fixed animations and missing content, and fixed the game's AI.
If you want a guide you should wait for the guy who made these patches to write it, I just followed his advice and developed these tools.

**Comment by nachotacos69** [comment]
You heard the guy @DarkGD123 might as well listen

**Comment by DarkGD123** [comment]
Okay then
