### ISSUE TITLE
What is GODVEIN?

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#7]
Inside where the CODEEATER.exe is located, I am confused on how GODVEIN works

**Comment by nachotacos69** [comment]
i have no idea too, i can only guess that its for somekind of repacking as some few people who used it dm'ed me of it usage, but we'll have to wait for the actual answer

**Comment by HaoJun0823** [comment]
CODE EATER is an experimental unpacking tool. When we didn't know what we should do, we wrote this Chinese language tool.
GOD VEIN is an experimental packaging tool. When the PRES format cannot be parsed, we use GOD VEIN to process specific files.
The above tools have been replaced by the latest tools, the new PRES packaging and unpacking and TR2 have fully achieved everything we want to do.
Currently CODE EATER and GOD VEIN are only used to batch process GNF, but I think there are other software that can do this better.
